name: Nightly

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions: read-all

env:
  OATF_CONFORMANCE_DIR: spec/conformance

jobs:
  proptest-extended:
    name: Property tests (extended)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: proptest-extended
      - name: Extended property tests
        run: cargo test --test property
        env:
          PROPTEST_CASES: "10000"

